In [2]:
import pandas as pd
df=pd.read_excel("/content/LIBRARY DATA SET.xlsx")

In [3]:
df

,Book_ID,Title,Author,Category,Cabinet,Rack,Row,Signal_Strength,Timestamp,Status
0,B001,The Adventures of Chronicles,Jordan Brown,Programming,4,5,4,-59,2024-12-11 10:01:00,Present
1,B002,The Dream of Shadows,Taylor Walker,History,3,3,5,-42,2024-12-11 10:02:00,Missing
2,B003,The Shadows of Mystery,Jordan Johnson,Science,5,3,4,-47,2024-12-11 10:03:00,Checked Out
3,B004,The Chronicles of Dream,Casey Walker,Fiction,4,1,1,-60,2024-12-11 10:04:00,Missing
4,B005,The Future of Adventures,Skyler Lee,Programming,3,4,2,-58,2024-12-11 10:05:00,Missing
...,...,...,...,...,...,...,...,...,...,...
195,B196,The Journey of Journey,Taylor Clark,Programming,4,1,1,-59,2024-12-11 13:16:00,Checked Out
196,B197,The Future of Adventures,Alex Anderson,Thriller,3,4,5,-40,2024-12-11 13:17:00,Missing
197,B198,The Chronicles of Quest,Dakota Brown,Thriller,4,1,4,-42,2024-12-11 13:18:00,Present
198,B199,The Journey of Adventures,Jordan Johnson,History,2,1,1,-53,2024-12-11 13:19:00,Present
199,B200,The Dream of Code,Riley Smith,Fiction,5,1,5,-57,2024-12-11 13:20:00,Checked Out

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Book_ID          200 non-null    object
 1   Title            200 non-null    object
 2   Author           200 non-null    object
 3   Category         200 non-null    object
 4   Cabinet          200 non-null    int64
 5   Rack             200 non-null    int64
 6   Row              200 non-null    int64
 7   Signal_Strength  200 non-null    int64
 8   Timestamp        200 non-null    datetime64[ns]
 9   Status           200 non-null    object
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 15.8+ KB

In [7]:
df.isnull().sum()

Book_ID            0
Title              0
Author             0
Category           0
Cabinet            0
Rack               0
Row                0
Signal_Strength    0
Timestamp          0
Status             0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df.drop_duplicates()

In [13]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['book_id', 'title', 'author', 'category', 'cabinet', 'rack', 'row',
       'signal_strength', 'timestamp', 'status'],
      dtype='object')

In [15]:
text_cols = df.select_dtypes(include="object").columns

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

In [17]:
df[text_cols] = df[text_cols].fillna("Unknown")

In [19]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
df[num_cols] = df[num_cols].fillna(0)

In [20]:
df.head()

,book_id,title,author,category,cabinet,rack,row,signal_strength,timestamp,status
0,B001,The Adventures of Chronicles,Jordan Brown,Programming,4,5,4,-59,2024-12-11 10:01:00,Present
1,B002,The Dream of Shadows,Taylor Walker,History,3,3,5,-42,2024-12-11 10:02:00,Missing
2,B003,The Shadows of Mystery,Jordan Johnson,Science,5,3,4,-47,2024-12-11 10:03:00,Checked Out
3,B004,The Chronicles of Dream,Casey Walker,Fiction,4,1,1,-60,2024-12-11 10:04:00,Missing
4,B005,The Future of Adventures,Skyler Lee,Programming,3,4,2,-58,2024-12-11 10:05:00,Missing

In [21]:
df.head(3)

,book_id,title,author,category,cabinet,rack,row,signal_strength,timestamp,status
0,B001,The Adventures of Chronicles,Jordan Brown,Programming,4,5,4,-59,2024-12-11 10:01:00,Present
1,B002,The Dream of Shadows,Taylor Walker,History,3,3,5,-42,2024-12-11 10:02:00,Missing
2,B003,The Shadows of Mystery,Jordan Johnson,Science,5,3,4,-47,2024-12-11 10:03:00,Checked Out

In [23]:
df.tail()

,book_id,title,author,category,cabinet,rack,row,signal_strength,timestamp,status
195,B196,The Journey of Journey,Taylor Clark,Programming,4,1,1,-59,2024-12-11 13:16:00,Checked Out
196,B197,The Future of Adventures,Alex Anderson,Thriller,3,4,5,-40,2024-12-11 13:17:00,Missing
197,B198,The Chronicles of Quest,Dakota Brown,Thriller,4,1,4,-42,2024-12-11 13:18:00,Present
198,B199,The Journey of Adventures,Jordan Johnson,History,2,1,1,-53,2024-12-11 13:19:00,Present
199,B200,The Dream of Code,Riley Smith,Fiction,5,1,5,-57,2024-12-11 13:20:00,Checked Out

In [24]:
df.tail(5)

,book_id,title,author,category,cabinet,rack,row,signal_strength,timestamp,status
195,B196,The Journey of Journey,Taylor Clark,Programming,4,1,1,-59,2024-12-11 13:16:00,Checked Out
196,B197,The Future of Adventures,Alex Anderson,Thriller,3,4,5,-40,2024-12-11 13:17:00,Missing
197,B198,The Chronicles of Quest,Dakota Brown,Thriller,4,1,4,-42,2024-12-11 13:18:00,Present
198,B199,The Journey of Adventures,Jordan Johnson,History,2,1,1,-53,2024-12-11 13:19:00,Present
199,B200,The Dream of Code,Riley Smith,Fiction,5,1,5,-57,2024-12-11 13:20:00,Checked Out