Import Libraries

In [ ]:
import pandas as pd
import numpy as np

Load Excel File

In [ ]:
df = pd.read_excel("LIBRARY DATA SET.xlsx")
print("Original Shape:", df.shape)
df.head()

Original Shape: (200, 10)

,Book_ID,Title,Author,Category,Cabinet,Rack,Row,Signal_Strength,Timestamp,Status
0,B001,The Adventures of Chronicles,Jordan Brown,Programming,4,5,4,-59,2024-12-11 10:01:00,Present
1,B002,The Dream of Shadows,Taylor Walker,History,3,3,5,-42,2024-12-11 10:02:00,Missing
2,B003,The Shadows of Mystery,Jordan Johnson,Science,5,3,4,-47,2024-12-11 10:03:00,Checked Out
3,B004,The Chronicles of Dream,Casey Walker,Fiction,4,1,1,-60,2024-12-11 10:04:00,Missing
4,B005,The Future of Adventures,Skyler Lee,Programming,3,4,2,-58,2024-12-11 10:05:00,Missing

Convert DataFrame to NumPy Array

In [ ]:
data = df.to_numpy()
print("NumPy Data Shape:", data.shape)

NumPy Data Shape: (200, 10)

Check Duplicate Rows Count (NumPy)

data_str = data.as

In [ ]:
data_str = data.astype(str)

unique_rows, counts = np.unique(data_str, axis=0, return_counts=True)

duplicate_rows = np.sum(counts > 1)

print("No of Duplicate Rows:", duplicate_rows)

No of Duplicate Rows: 0

Convert Back to DataFrame

In [ ]:
df_unique = pd.DataFrame(unique_rows, columns=df.columns)
df_unique.head()

,Book_ID,Title,Author,Category,Cabinet,Rack,Row,Signal_Strength,Timestamp,Status
0,B001,The Adventures of Chronicles,Jordan Brown,Programming,4,5,4,-59,2024-12-11 10:01:00,Present
1,B002,The Dream of Shadows,Taylor Walker,History,3,3,5,-42,2024-12-11 10:02:00,Missing
2,B003,The Shadows of Mystery,Jordan Johnson,Science,5,3,4,-47,2024-12-11 10:03:00,Checked Out
3,B004,The Chronicles of Dream,Casey Walker,Fiction,4,1,1,-60,2024-12-11 10:04:00,Missing
4,B005,The Future of Adventures,Skyler Lee,Programming,3,4,2,-58,2024-12-11 10:05:00,Missing